# Anophel Chat service configuration file
server:
  host: "0.0.0.0"
  port: 8080
  type: "tcp" # tcp or websocket
  maxClients: 100
  readTimeout : 5 # per second
  writeTimeout: 5 # per second

security:
  requirePassword: false
  password: "1234"
  hashMessage: true
  hashAlgorithm: "hmac-sha256"
  hashKey: "supersecret"

rateLimit:
  messagePerSecond: 5
  burst: 5

message:
  maxLength : 1000

log:
  enableLogging: false
  file: "chat.log"

tls:
  tlsRequire: false # Enable TLS
  certFile: "tls/server.crt" # Certificate file
  keyFile: "tls/server.key" # Private key file
  minVersion: "TLS12" # Minimum TLS version
